#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting Network Watchdog Service"
    systemctl enable waggle-network-watchdog.service
    systemctl start waggle-network-watchdog.service || true
    ;;
esac
