name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # checkout all git history
    - name: run tests and coverage
      run: ./build.sh -f
