name: Unit Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit_test:
    name: Unit Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Accelerated Test Run
        run: ./test.sh
